"""Wastebin AI Detector - self-contained detection core.

Pure numpy + Pillow, no Home Assistant imports: everything in this
package can be exercised offline (calibration CLI, tests) and is reused
unchanged by the Home Assistant integration layer.
"""

from .ccl import largest_component_area
from .color import (
    MixtureFit,
    circular_dist_deg,
    circular_mean_deg,
    fit_vonmises_uniform_mixture,
    rgb_to_hsv,
    vonmises_kappa_from_resultant,
)
from .detect import (
    BinResult,
    DetectionResult,
    bin_mask,
    detect,
    detect_file,
    is_uncertain,
)
from .errors import (
    CalibrationError,
    ImageLoadError,
    ProfileError,
    RoiError,
    WastebinError,
)
from .imageio import (
    extract_working_roi,
    load_image_rgb,
    load_image_rgb_bytes,
    roi_to_pixels,
)
from .learn import (
    derive_quality_gates,
    learn_area_threshold,
    learn_color_model,
    learn_profile,
)
from .profile import (
    REL_EPS,
    SCHEMA_VERSION,
    BinModel,
    Profile,
    Rect,
    Roi,
    load_profile,
    profile_from_dict,
    profile_to_dict,
    save_profile,
    validate_profile,
)
from .store import (
    BinDecl,
    CalibrationStore,
    ImageEntry,
    SampleRect,
    clamp_unit_rect,
    image_rect_in_roi,
    learning_view,
    load_store,
    migrate_store_dict_v1_to_v2,
    resolve_image_path,
    roi_contains,
    roi_equal,
    roi_rect_to_image_rect,
    save_store,
    store_from_dict,
    store_to_dict,
    validate_store,
)

__all__ = [
    "bin_mask",
    "BinDecl",
    "BinModel",
    "BinResult",
    "CalibrationError",
    "CalibrationStore",
    "circular_dist_deg",
    "circular_mean_deg",
    "clamp_unit_rect",
    "derive_quality_gates",
    "detect",
    "detect_file",
    "DetectionResult",
    "extract_working_roi",
    "fit_vonmises_uniform_mixture",
    "image_rect_in_roi",
    "ImageEntry",
    "ImageLoadError",
    "is_uncertain",
    "largest_component_area",
    "learn_area_threshold",
    "learn_color_model",
    "learn_profile",
    "learning_view",
    "load_image_rgb",
    "load_image_rgb_bytes",
    "load_profile",
    "load_store",
    "migrate_store_dict_v1_to_v2",
    "MixtureFit",
    "Profile",
    "profile_from_dict",
    "profile_to_dict",
    "ProfileError",
    "Rect",
    "REL_EPS",
    "resolve_image_path",
    "rgb_to_hsv",
    "Roi",
    "roi_contains",
    "roi_equal",
    "roi_rect_to_image_rect",
    "roi_to_pixels",
    "RoiError",
    "SampleRect",
    "save_profile",
    "save_store",
    "SCHEMA_VERSION",
    "store_from_dict",
    "store_to_dict",
    "validate_profile",
    "validate_store",
    "vonmises_kappa_from_resultant",
    "WastebinError",
]
